### ISSUE TITLE
prevent click event on selected element

### ISSUE THREAD

**Issue by danielravina** [luoye-fe/dom-inspector#14]
Hi there,

Thank you for making this cool project.
is it possible to somehow disable the click event when an element is selected?

Thanks

**Comment by luoye-fe** [comment]
Maybe you can directly disable the click event when enable dom inspect.

```css
.inspect-content * {
    /* disable all mouse events on subElements */
    pointer-events: none; 
}
```
OR
```js
let enableInspector = false; // just modify that variable to disable all clics events

document.addEventListener("click", freezeClicFn, true);

function freezeClicFn(e) {
    if (freezeClic) {
        e.stopPropagation();
        e.preventDefault();
    }
}
```
